apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: azure-cluster
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.1.0.0/16"]
    services:
      cidrBlocks: ["10.2.0.0/16"]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: azure-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureCluster
    name: azure-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: azure-cluster
  namespace: default
spec:
  location: westus2
  resourceGroup: azure-cluster-rg
  networkSpec:
    vnet:
      name: azure-cluster-vnet
      cidrBlock: "10.1.0.0/16"
    subnets:
    - name: azure-cluster-subnet
      cidrBlock: "10.1.0.0/24"
      role: node
  controlPlaneEndpoint:
    host: "10.1.1.1"
    port: 6443
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: azure-control-plane
  namespace: default
spec:
  replicas: 3
  version: v1.33.4
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureMachineTemplate
    name: azure-control-plane-template
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 10.1.1.1
      controlPlaneEndpoint: "10.1.1.1:6443"
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: azure
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: azure
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureMachineTemplate
metadata:
  name: azure-control-plane-template
  namespace: default
spec:
  template:
    spec:
      vmSize: Standard_D2s_v3
      osDisk:
        diskSizeGB: 30
        osType: Linux
      image:
        marketplace:
          name: "0001-com-ubuntu-server-focal"
          publisher: "Canonical"
          offer: "0001-com-ubuntu-server-focal"
          sku: "20_04-lts-gen2"
          version: "latest"
